# Generated by Django 3.2.9 on 2021-11-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guitars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('guitar_model', models.CharField(max_length=25)),
                ('tier', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('owner', models.CharField(blank=True, max_length=25, null=True)),
                ('handed', models.CharField(blank=True, max_length=25, null=True)),
                ('no_strings', models.CharField(blank=True, max_length=25, null=True)),
                ('approx_age_years', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('condition', models.CharField(blank=True, max_length=25, null=True)),
                ('construction', models.CharField(blank=True, max_length=25, null=True)),
                ('body_wood', models.CharField(blank=True, max_length=25, null=True)),
                ('body_top', models.CharField(blank=True, max_length=25, null=True)),
                ('tuners', models.CharField(blank=True, max_length=25, null=True)),
                ('frets', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('scale_length', models.CharField(blank=True, max_length=25, null=True)),
                ('neck_wood', models.CharField(blank=True, max_length=25, null=True)),
                ('neck_profile', models.CharField(blank=True, max_length=25, null=True)),
                ('no_pickups', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('pickups_desc', models.TextField()),
                ('controls', models.CharField(blank=True, max_length=25, null=True)),
                ('owners_additional_comments', models.TextField()),
                ('rating_condition', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('rating_overall', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('image_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.category')),
            ],
        ),
    ]
