# Generated by Django 3.2.9 on 2021-11-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guitars',
            new_name='Guitar',
        ),
    ]
