# Generated by Django 3.2.9 on 2021-11-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0003_auto_20211112_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='rating_condition',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='rating_overall',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
