# Generated by Django 3.2.9 on 2021-11-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0006_auto_20211113_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='category',
            field=models.ForeignKey(choices=[('1', 'Electric'), ('2', 'Bass'), ('3', 'Acoustic')], default='1', on_delete=django.db.models.deletion.PROTECT, to='guitars.category'),
        ),
    ]
