# Generated by Django 3.2.9 on 2021-11-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0007_alter_guitar_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='guitar',
            name='handed',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='Right', max_length=5),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='tier',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], default='Bronze', max_length=10),
        ),
    ]
