# Generated by Django 3.2.9 on 2021-12-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0013_alter_guitar_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='condition',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Cosmetic', 'Well Used (displays cosmetic signs of use only)'), ('Defective', 'Some form of damage / wear which affects performance.')], default='Good', max_length=250),
        ),
    ]
