# Generated by Django 3.2.9 on 2022-01-22 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guitars', '0014_alter_guitar_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
