# Generated by Django 3.2.9 on 2022-01-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0015_guitar_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use')], default='Available', max_length=25),
        ),
    ]
