# Generated by Django 3.2.9 on 2022-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0016_alter_guitar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='no_strings',
            field=models.DecimalField(decimal_places=0, default=6, max_digits=2),
        ),
    ]
