# Generated by Django 3.2.9 on 2022-01-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default='TRUE')),
                ('canx_date', models.DateTimeField()),
                ('Plec_Plat', models.IntegerField(blank=True, default=0, null=True)),
                ('Plec_Gold', models.IntegerField(blank=True, default=0, null=True)),
                ('Plec_Slvr', models.IntegerField(blank=True, default=0, null=True)),
                ('Plec_Brnz', models.IntegerField(blank=True, default=0, null=True)),
                ('start_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_start_date', to='checkout.order')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_sub_type', to='checkout.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_user', to='checkout.order')),
            ],
        ),
    ]
