# Generated by Django 3.2.9 on 2022-01-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0006_alter_order_order_number'),
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='Plec_Brnz',
            new_name='plec_brnz',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='Plec_Gold',
            new_name='plec_gold',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='Plec_Plat',
            new_name='plec_plat',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='Plec_Slvr',
            new_name='plec_slvr',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='accounts',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='canx_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
