# Generated by Django 3.2.9 on 2022-01-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_order_number'),
        ('site_admin', '0002_auto_20220126_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='canx_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
    ]
