# Generated by Django 3.2.9 on 2022-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_alter_accounts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='temp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
