# Generated by Django 3.2.9 on 2022-01-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0007_accounts_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='temp',
        ),
    ]
