# Generated by Django 3.2.9 on 2022-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0010_auto_20220127_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='user',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='plectrum_balance',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
