# Generated by Django 3.2.9 on 2022-01-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_date'),
        ('site_admin', '0011_auto_20220128_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='canx_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='checkout.order'),
        ),
    ]
