# Generated by Django 3.2.9 on 2022-01-29 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0014_auto_20220129_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar_loans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guitar_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
