# Generated by Django 3.2.9 on 2021-11-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profile',
            new_name='member_profile',
        ),
    ]
