# Generated by Django 3.2.9 on 2021-11-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='delivery',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AddField(
            model_name='subscription',
            name='re_stringed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='set_up',
            field=models.BooleanField(default=False),
        ),
    ]
