# Generated by Django 3.2.9 on 2021-11-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='default_email',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='default_full_name',
        ),
    ]
