# Generated by Django 3.2.9 on 2022-01-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20211121_1230'),
        ('members', '0002_auto_20211129_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('canx_date', models.DateTimeField(auto_now_add=True)),
                ('member_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.memberprofile')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscription')),
            ],
        ),
    ]
