# Generated by Django 3.2.9 on 2022-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_membersplans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersplans',
            name='canx_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='membersplans',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
