# Generated by Django 3.2.9 on 2022-01-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20220122_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembersPlans',
        ),
    ]
